model:
    seq_length: 50
    input_dim: 217
    num_joints: 31

    n_layers: 8
    n_head: 8
    d_k: 64
    d_v: 64
    d_model: 256
    d_inner: 512
    n_past: 10
    n_future: 10
    n_trans: 30
data:
    data_dir: './data/mocap_test.npz'
    data_set: 'mocap'
    offsets: [[ 0.     ,  0.     ,  0.     ],
              [ 0.     ,  0.     ,  0.     ],
              [ 1.36306, -1.79463,  0.83929],
              [ 2.44811, -6.72613,  0.     ],
              [ 2.5622 , -7.03959,  0.     ],
              [ 0.15764, -0.43311,  2.32255],
              [ 0.     ,  0.     ,  0.     ],
              [-1.30552, -1.79463,  0.83929],
              [-2.54253, -6.98555,  0.     ],
              [-2.56826, -7.05623,  0.     ],
              [-0.16473, -0.45259,  2.36315],
              [ 0.     ,  0.     ,  0.     ],
              [ 0.02827,  2.03559, -0.19338],
              [ 0.05672,  2.04885, -0.04275],
              [ 0.     ,  0.     ,  0.     ],
              [-0.05417,  1.74624,  0.17202],
              [ 0.10407,  1.76136, -0.12397],
              [ 0.     ,  0.     ,  0.     ],
              [ 3.36241,  1.20089, -0.31121],
              [ 4.983  , -0.     , -0.     ],
              [ 3.48356, -0.     , -0.     ],
              [ 0.     ,  0.     ,  0.     ],
              [ 0.71526, -0.     , -0.     ],
              [ 0.     ,  0.     ,  0.     ],
              [ 0.     ,  0.     ,  0.     ],
              [-3.1366 ,  1.37405, -0.40465],
              [-5.2419 , -0.     , -0.     ],
              [-3.44417, -0.     , -0.     ],
              [ 0.     ,  0.     ,  0.     ],
              [-0.62253, -0.     , -0.     ],
              [ 0.     ,  0.     ,  0.     ]]
    parents: [-1,  0,  1,  2,  3,  4,  0,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15, 13, 17, 18, 19, 20, 21, 20, 13, 24, 25, 26, 27, 28, 27]
    joints_to_remove: [ ]
    offset: 20
    num_workers: 4
test:
    batch_size: 1
    seed: 1234
    dropout: 0.1

    loss_pose_weight: 0.01
    loss_quat_weight: 1.0
    loss_position_weight: 1.0


    save_img: False
    save_gif: False
    save_pose: False
    save_bvh: True
    debug: False
    cuda: True

    model_dir: './checkpoints/train_mocap_01/epoch_1000.pt'
    output_dir: './outputs/test_01_1000_mocap/bvh'
    img_dir: './outputs/test_01_1000_mocap/img'
    gif_dir: './outputs/test_01_1000_mocap/gif'